// Generated by CoffeeScript 1.9.3
(function() {
  var BrowserWindow, app, checks, mainWindow, setup;

  checks = require('./libs/checks.js');

  setup = function(root) {
    return checks.checkBash;
  };

  app = require('app');

  BrowserWindow = require('browser-window');

  require('crash-reporter').start();

  mainWindow = null;

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      app.quit();
    }
  });

  app.on('ready', function() {
    mainWindow = new BrowserWindow({
      width: 800,
      height: 600
    });
    mainWindow.loadUrl('file://' + __dirname + '/views/index.html');
    mainWindow.webContents.openDevTools();
    mainWindow.on('closed', function() {
      mainWindow = null;
    });
  });

}).call(this);
