// Generated by CoffeeScript 1.9.3
(function() {
  var BrowserWindow, app, checks, delay, mainWindow, setup, spawn;

  checks = require('./libs/checks.js');

  spawn = require('child_process').spawn;

  delay = require('delayed').delay;

  setup = require('./libs/setup.js');

  setup = function(root) {
    return checks.checkBash;
  };

  app = require('app');

  BrowserWindow = require('browser-window');

  require('crash-reporter').start();

  mainWindow = null;

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      app.quit();
    }
  });

  app.on('ready', function() {
    mainWindow = new BrowserWindow({
      width: 800,
      height: 600
    });
    mainWindow.loadUrl('file://' + __dirname + '/views/index.html');
    setup.begin('gui', mainWindow);
    mainWindow.on('closed', function() {
      mainWindow = null;
    });
  });

}).call(this);
